name: Docker Image CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        tag:
          - { name: latest, file: AMPDockerFile }
          - { name: java, file: AMPDockerFileJava }
          - { name: node, file: AMPDockerFileNode }
          - { name: xvfb, file: AMPDockerFileXvfb }
          - { name: python3, file: AMPDockerFilePython3 }
          - { name: wine, file: AMPDockerFileWine }
          - { name: mono, file: AMPDockerFileMono }
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.tag.file }}
          platforms: linux/amd64
          push: true
          tags: ghcr.io/frozensoda/amp-docker-images:${{ matrix.tag.name }}
